import { prisma } from '@/lib/db'

/** Canon cast — pre-seeded, met:false until player meets them. */
const CANON_NPCS = [
  {
    name: 'Тане',
    bond: 0,
    tribe: 'Кай-Тору',
    notes: 'Молодий воїн, син/близький до вождівської лінії. Ніжний, цікавиться Ларою.',
    met: false,
    personality: 'сором\'язливий, лагідний, допитливий, традиційний, вірний',
    archetype: 'воїн',
    attitude: 'curious',
    trust: 40,
    fear: 10,
    respect: 45,
    location: 'Селище Кай-Тору',
  },
  {
    name: 'Лея',
    bond: 0,
    tribe: 'Кай-Тору',
    notes: 'Жінка племені, складна історія з Джеком; має зв\'язок із Тане.',
    met: false,
    personality: 'хитра, пристрасна, ревнива, гостинна, амбіційна',
    archetype: 'танцівниця',
    attitude: 'wary',
    trust: 30,
    fear: 5,
    respect: 40,
    location: 'Джунглі',
  },
  {
    name: 'Джек Вейн',
    bond: 1,
    tribe: 'Зовнішній світ',
    notes: 'Провідник/контрабандист. Знає частину таємниць острова. Розуміє згоду.',
    met: false,
    personality: 'цинічний, практичний, стриманий, вірний слову, досвідчений',
    archetype: 'провідник',
    attitude: 'neutral',
    trust: 55,
    fear: 0,
    respect: 50,
    location: 'Руїни стародавнього міста',
  },
  {
    name: 'Макаї',
    bond: 0,
    tribe: 'Кай-Тору',
    notes: 'Вождь племені. Авторитетний, говорить наказами.',
    met: false,
    personality: 'домінантний, традиційний, територіальний, мудрий, жорсткий',
    archetype: 'вождь',
    attitude: 'wary',
    trust: 20,
    fear: 15,
    respect: 70,
    location: 'Селище Кай-Тору',
  },
  {
    name: 'Найя',
    bond: 0,
    tribe: 'Кай-Тору',
    notes: 'Шаманка. Знає про амулет і храм більше, ніж каже.',
    met: false,
    personality: 'загадкова, мудра, маніпулятивна, духовна, терпляча',
    archetype: 'шаман',
    attitude: 'curious',
    trust: 35,
    fear: 5,
    respect: 65,
    location: 'Храм насолоди',
  },
  {
    name: 'Араху',
    bond: 0,
    tribe: 'Острів',
    notes: 'Дух/присутність острова — може проявлятися через амулет або видіння.',
    met: false,
    personality: 'давній, байдужий до моралі, хтивий до енергії, загадковий',
    archetype: 'дух',
    attitude: 'neutral',
    trust: 10,
    fear: 20,
    respect: 80,
    location: 'Священна гора',
  },
  // --- other tribes (canon, met:false until contact) ---
  {
    name: 'Ксерон',
    bond: 0,
    tribe: 'Кентаври',
    notes: 'Ватажок табуна. Гордий; близькість лише після змагання.',
    met: false,
    personality: 'гордий, змагальний, шляхетний, жорсткий, чесний у випробуваннях',
    archetype: 'ватажок',
    attitude: 'wary',
    trust: 25,
    fear: 5,
    respect: 60,
    location: 'Землі кентаврів',
  },
  {
    name: 'Іпполіта',
    bond: 0,
    tribe: 'Кентаври',
    notes: 'Найшвидша в табуні. Може закохатися в сильну Лару (лесбі-лінія).',
    met: false,
    personality: 'швидка, горда, пристрасна, незалежна, вірна переможцям',
    archetype: 'воїн',
    attitude: 'curious',
    trust: 35,
    fear: 5,
    respect: 50,
    location: 'Землі кентаврів',
  },
  {
    name: 'Гор-Ак',
    bond: 0,
    tribe: 'Мінотаври',
    notes: 'Ватажок лабіринту. Жорстокий, не тупий; бачить слабших як гарем/здобич.',
    met: false,
    personality: 'домінантний, жорстокий, розумний, територіальний, гордий',
    archetype: 'ватажок',
    attitude: 'hostile',
    trust: 10,
    fear: 0,
    respect: 40,
    location: 'Лабіринт мінотаврів',
  },
  {
    name: 'Міра',
    bond: 0,
    tribe: 'Мінотаври',
    notes: 'Воїнка поза гаремом. Шукає спосіб скинути Гор-Ака; потенційний союз.',
    met: false,
    personality: 'бунтівна, сильна, обережна, цілеспрямована, чесна',
    archetype: 'воїн',
    attitude: 'wary',
    trust: 30,
    fear: 15,
    respect: 45,
    location: 'Лабіринт мінотаврів',
  },
  {
    name: 'Кіра',
    bond: 0,
    tribe: 'Гієноїди',
    notes: 'Матріарх. Розумна й жорстока; гарем як влада, не романтика.',
    met: false,
    personality: 'маніпулятивна, домінантна, розумна, жорстока, харизматична',
    archetype: 'ватажок',
    attitude: 'curious',
    trust: 15,
    fear: 5,
    respect: 55,
    location: 'Територія гієноїдів',
  },
  {
    name: 'Зек',
    bond: 0,
    tribe: 'Гієноїди',
    notes:
      'ВІДСТУПНИК: сам вийшов зі стаї Кіри. Був «улюбленим» розплідником, зірвав ритуал повного підкорення, втік у ніч рейду. На ньому death-scent (мітка смерті) — стая мусить повернути або вбити. Знає обхідні стежки й слабкі місця патрулів. Арка: сліди → зустріч → притулок → таємниця втечі → мисливці → зняти мітку → суд Кіри → доля.',
    met: false,
    personality:
      'полохливий, вдячний, хитрий, відданий захиснику, знервований, сексуально досвідчений, жадібний до свободи',
    archetype: 'вигнанець',
    attitude: 'fearful',
    trust: 40,
    fear: 60,
    respect: 30,
    location: 'Джунглі',
  },
  {
    name: 'Грух',
    bond: 0,
    tribe: 'Свинолюди',
    notes: 'Ватажок боліт. Хоче Лару як трофей; низький інтелект, висока небезпека.',
    met: false,
    personality: 'тупий, жадібний, агресивний, похотливий, впертий',
    archetype: 'ватажок',
    attitude: 'hostile',
    trust: 5,
    fear: 0,
    respect: 10,
    location: 'Болота свинолюдів',
  },
  {
    name: 'Свиноматка',
    bond: 0,
    tribe: 'Свинолюди',
    notes: 'Стара; керує розмноженням і «обміном». Може «захистити» за ціну.',
    met: false,
    personality: 'хитра, цинічна, меркантильна, спокійна, жорстока',
    archetype: 'торговка',
    attitude: 'neutral',
    trust: 20,
    fear: 10,
    respect: 25,
    location: 'Болота свинолюдів',
  },
]

export async function seedCanonNpcs() {
  for (const npc of CANON_NPCS) {
    await prisma.relationship.upsert({
      where: { name: npc.name },
      update: {
        // Don't overwrite if already met/progressed — only fill empty personality
      },
      create: {
        ...npc,
        metOnDay: 0,
      },
    })
  }
}
